<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-SBMFI0I6" failures="1" tests="10" name="newtours.tests.BookFlightTest" time="9.357" errors="0" timestamp="2021-11-03T20:07:44 IST" skipped="0">
  <testcase classname="newtours.tests.BookFlightTest" name="flightConfirmationPage" time="0.520">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at utils.ActionEngine.assertEqualsString_custom(ActionEngine.java:114)
at newtours.tests.BookFlightTest.flightConfirmationPage(BookFlightTest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- flightConfirmationPage -->
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="registrationPage" time="1.427"/>
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="findFlightPage" time="0.875"/>
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="registrationConfirmationPage" time="0.402"/>
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="registrationPage" time="1.164"/>
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="flightDetailsPage" time="1.798"/>
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="findFlightPage" time="0.632"/>
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="registrationConfirmationPage" time="0.341"/>
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="flightDetailsPage" time="1.786"/>
  <system-out/>
  <testcase classname="newtours.tests.BookFlightTest" name="flightConfirmationPage" time="0.412"/>
  <system-out/>
</testsuite> <!-- newtours.tests.BookFlightTest -->
