<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-SBMFI0I6" failures="1" tests="8" name="book-flight-1" time="53.484" errors="0" timestamp="2021-11-03T20:07:32 IST">
  <testcase classname="newtours.tests.BookFlightTest" name="registrationPage" time="1.427"/>
  <testcase classname="newtours.tests.BookFlightTest" name="registrationConfirmationPage" time="0.402"/>
  <testcase classname="newtours.tests.BookFlightTest" name="flightDetailsPage" time="1.798"/>
  <testcase classname="newtours.tests.BookFlightTest" name="registrationPage" time="1.164"/>
  <testcase classname="newtours.tests.BookFlightTest" name="findFlightPage" time="0.632"/>
  <testcase classname="newtours.tests.BookFlightTest" name="registrationConfirmationPage" time="0.341"/>
  <testcase classname="newtours.tests.BookFlightTest" name="flightConfirmationPage" time="0.52">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at utils.ActionEngine.assertEqualsString_custom(ActionEngine.java:114)
at newtours.tests.BookFlightTest.flightConfirmationPage(BookFlightTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- flightConfirmationPage -->
  <testcase classname="newtours.tests.BookFlightTest" name="flightDetailsPage" time="1.786"/>
</testsuite> <!-- book-flight-1 -->
